---
title: "example1"
author: "zjg"
date: "2022-12-01"
output: html_document
---

download.file(url="https://raw.githubusercontent.com/cambiotraining/reproducibility-training/master/data/gapminder_data.csv", destfile="data/gapminder_data.csv")

The example

#this is a header

```{r load-data, message=FALSE}
library(tidyverse)
# load the dataset
pop_data <-read.csv("data/gapminder_data.csv")

#create a table with data from European countries in 2007 showing the countries with the largest life expectancy at the top 

euro_data_tbl <- pop_data %>% 
                    filter(continent == "Europe" & year == 2007) %>% 
                    select(-continent, -year) %>% #removes these columns as they are filtered
                    arrange(desc(lifeExp)) %>% 
                    rename("Country" = country, "Population Size" = pop, 
                      "Life Expectancy" = lifeExp, "GDP" = gdpPercap)


```

we have loaded our data

```{r create-table}
library(kableExtra)

euro_data_tbl %>%
  kbl() %>%
  kable_styling(bootstrap_options = c("striped", "hover")) %>%
  column_spec(1:3, bold = T) %>%
  row_spec(3:5, bold = T, color = "white", background = "#D7261E")

  
```


```{r page-table , message=FALSE}
library(rmarkdown)

paged_table(euro_data_tbl)

```



```{r add-image}
library(ggplot2)
euro_data_fig <- pop_data %>% 
                    filter(continent == "Europe")%>% 
                    mutate(year=as_factor(year))
euro_data_fig %>%
  ggplot(aes(x= year, y= lifeExp)) +
  geom_violin()


```







